In [60]:
import numpy as np

In [61]:
%%markdown
# Recursion - Examples
## Factorial
\begin{align}
!n &= !(n-1).n \\
!0 &= 1
\end{align}

# Recursion - Examples
## Factorial
\begin{align}
!n &= !(n-1).n \\
!0 &= 1
\end{align}

In [62]:
def factorial (n):
    if (n >= 1):
        return (n-1)*n
    else:
        return 1


In [63]:
n = 4
print ("Factorial of ", n, factorial(n))

Factorial of  4 12


In [80]:
%%markdown
## Determinant of a matrix
* [Laplace's formula](http://en.wikipedia.org/wiki/Determinant#Laplace's_formula_and_the_adjugate_matrix)
\begin{align}
\det(A)=\sum _{j=1}^{n}(-1)^{i+j}a_{i,j}M_{i,j} \text{ for a fixed } i
\end{align}
* With $i = 1$
\begin{align}
\det(A)=\sum _{j=1}^{n}(-1)^{j+1}a_{1,j}M_{1,j}
\end{align}

## Determinant of a matrix
* [Laplace's formula](http://en.wikipedia.org/wiki/Determinant#Laplace's_formula_and_the_adjugate_matrix)
\begin{align}
\det(A)=\sum _{j=1}^{n}(-1)^{i+j}a_{i,j}M_{i,j} \text{ for a fixed } i
\end{align}
* With $i = 1$
\begin{align}
\det(A)=\sum _{j=1}^{n}(-1)^{j+1}a_{1,j}M_{1,j}
\end{align}

In [194]:
%%markdown
A = \begin{bmatrix}
 -2 & 2 & -3 \\
 -1 & 1 &  3 \\
  2 & 0 & -1
\end{bmatrix}

along the second column ($j = 2$ and the sum runs over $i$) is given by,
\begin{align}
det(A) &= (-1)^{1+2} \cdot 2 \cdot \begin{vmatrix}-1&3 \\ 2&-1\end{vmatrix} + (-1)^{2+2} \cdot 1 \cdot \begin{vmatrix} -2&-3 \\ 2&-1 \end{vmatrix} + (-1)^{3+2} \cdot 0 \cdot \begin{vmatrix} -2&-3\\-1&3\end{vmatrix} \\
 &= (-2) \cdot ((-1) \cdot (-1) - 2 \cdot 3) + 1 \cdot ((-2) \cdot (-1)-2 \cdot (-3)) \\
 &= (-2) \cdot (-5)+8=18.
\end{align}

along the first column ($j = 1$ and the sum runs over $i$) is given by,
\begin{align}
det(A) &= (-1)^{1+1} \cdot -2 \cdot \begin{vmatrix} 1&3 \\ 0&-1\end{vmatrix} + (-1)^{2+1} \cdot -1 \cdot \begin{vmatrix} 2&-3 \\ 0&-1 \end{vmatrix} + (-1)^{3+1} \cdot 2 \cdot \begin{vmatrix} 2&-3\\1&3\end{vmatrix} \\
 &= -2 \cdot (1 \cdot (-1)) + 1 \cdot (2 \cdot (-1)) + 2 \cdot (2 \cdot 3 - 1 \cdot (-3)) \\
 &= -2 \cdot (-1) + 1 \cdot (-2 ) + 2 \cdot (6 + 3) \\
 &= 2 -2 + 2 \cdot 9 = 18.
\end{align}

A = \begin{bmatrix}
 -2 & 2 & -3 \\
 -1 & 1 &  3 \\
  2 & 0 & -1
\end{bmatrix}

along the second column ($j = 2$ and the sum runs over $i$) is given by,
\begin{align}
det(A) &= (-1)^{1+2} \cdot 2 \cdot \begin{vmatrix}-1&3 \\ 2&-1\end{vmatrix} + (-1)^{2+2} \cdot 1 \cdot \begin{vmatrix} -2&-3 \\ 2&-1 \end{vmatrix} + (-1)^{3+2} \cdot 0 \cdot \begin{vmatrix} -2&-3\\-1&3\end{vmatrix} \\
 &= (-2) \cdot ((-1) \cdot (-1) - 2 \cdot 3) + 1 \cdot ((-2) \cdot (-1)-2 \cdot (-3)) \\
 &= (-2) \cdot (-5)+8=18.
\end{align}

along the first column ($j = 1$ and the sum runs over $i$) is given by,
\begin{align}
det(A) &= (-1)^{1+1} \cdot -2 \cdot \begin{vmatrix} 1&3 \\ 0&-1\end{vmatrix} + (-1)^{2+1} \cdot -1 \cdot \begin{vmatrix} 2&-3 \\ 0&-1 \end{vmatrix} + (-1)^{3+1} \cdot 2 \cdot \begin{vmatrix} 2&-3\\1&3\end{vmatrix} \\
 &= -2 \cdot (1 \cdot (-1)) + 1 \cdot (2 \cdot (-1)) + 2 \cdot (2 \cdot 3 - 1 \cdot (-3)) \\
 &= -2 \cdot (-1) + 1 \cdot (-2 ) + 2 \cdot (6 + 3) \\
 &= 2 -2 + 2 \cdot 9 = 18.
\end{align}

In [224]:
def extractMij(A, i, verbose = False):
    """Extract the minor M_ij of A, where we take j=0"""
    n = len(A)
    M0 = A[:, np.r_[1:n]]
    Mi0 = None

    if (i == 0):
        Mi0 = M0[list(range(1, n)), :]        
    else:
        Mi0 = M0[list(range(0, i)) + list(range(i+1, n)), :]
    return Mi0


In [249]:
def determinant(A, verbose = False):
    """Calculate the determinant of the A matrix, according to the Lagrange algorithm.
       Note that the matrix indices in classical litterature (including in the
       reference document, ie Wikipedia) are usually ranging between 1 and n,
       where as the indices in NumPy are ranging between 0 and n-1.
       Hence, the variable is here called jm1 (standing for j minus -1).
       We select the first column (jm1=0), and go through the rows."""
    n = len(A)
    det = 0
    
    if (verbose == True):
        print("A (size = %s): \n" % n, str(A))
        print("Determinant of A: ", determinant(A))
    
    if (n == 2):
        det = (A[0, 0] * A[1, 1] - A[1, 0] * A[0, 1])
    else:
        for im1 in range(0, n):
            Mij = extractMij(A, im1)
            aij = A[im1, 0]
            det += (-1)**im1 * aij * determinant(Mij)
            
            if (verbose == True):
                print("(-1)**(i+j), aij, det(Mij) for (i, j) = (%s, 1): " % i, (-1)**i, aij, determinant(Mij))
                print("Mij for (i, j) = (%s, 1): \n" % i, str(Mij))            
    return det

In [253]:
A = np.matrix([[-2, 2, -3], [-1, 1, 3], [2, 0, -1]])
determinant(A, verbose=True)

A (size = 3): 
 [[-2  2 -3]
 [-1  1  3]
 [ 2  0 -1]]
Determinant of A:  18
(-1)**(i+j), aij, det(Mij) for (i, j) = (2, 1):  1 -2 -1
Mij for (i, j) = (2, 1): 
 [[ 1  3]
 [ 0 -1]]
(-1)**(i+j), aij, det(Mij) for (i, j) = (2, 1):  1 -1 -2
Mij for (i, j) = (2, 1): 
 [[ 2 -3]
 [ 0 -1]]
(-1)**(i+j), aij, det(Mij) for (i, j) = (2, 1):  1 2 9
Mij for (i, j) = (2, 1): 
 [[ 2 -3]
 [ 1  3]]


18

In [254]:
A = np.random.randint(1, 10, size=(5, 5))
determinant(A)

5469